name: CI

on:
  push:
    branches:
      - main
      - beta
      - dev
  pull_request:
    branches: 
      - main
      - beta
      - dev
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-
      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

      - name: Set up protoc-gen-go-grpc
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go-grpc@latest

      - name: Build
        run:  make
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          destination-github-username: 'isd-sgcu'
          destination-repository-name: 'rpkm66-go-proto'
          user-email: isd.team.sgcu@gmail.com
          target-branch: ${{ github.base_ref }}
          create-target-branch-if-needed: true